### ISSUE TITLE
Chrome error message

### ISSUE THREAD

**Issue by bnjmnsbl** [stefanw/voebbot#1]
<img width="677" alt="Bildschirmfoto 2021-03-17 um 10 22 50" src="https://user-images.githubusercontent.com/11134234/111444605-d6e9c780-870a-11eb-84bf-ec625abc9c97.png">

Plugin still seems to work fine. 

Chrome V.  89.0.4389.90

Fantastic tool, cheers!

**Comment by tillnagel** [comment]
Same warning message in Chrome Mac 89.0.4389.90. Plugin works still.

**Comment by stefanw** [comment]
The unrecognized manifest key can be ignored. The "cannot read property innerText of null" is a problem with title extraction from a page. What URL did you visit?

(This thing needs a test suite!)

**Comment by stefanw** [comment]
Closing as it is unclear which site triggered the error. Please open a new issue for specific sites not working.
