### ISSUE TITLE
Aus lizenzrechtlichen Gründen steht Genios zur Zeit leider nicht zur Verfügung.

### ISSUE THREAD

**Issue by stefanw** [stefanw/voebbot#10]
VÖBB-Genios account is blocked. This extension is the reason. More info to follow soon.

**Comment by PascalKoe** [comment]
Von der VÖBB Webseite:
"Aus lizenzrechtlichen Gründen steht Genios zur Zeit leider nicht zur Verfügung."

**Comment by stefanw** [comment]
Läuft wieder, aber mit Captcha ab und zu.
