### ISSUE TITLE
WISO Zugang für Studierende

### ISSUE THREAD

**Issue by PascalKoe** [stefanw/voebbot#12]
Einige Hochschulen und Universitäten bieten den Studierenden einen Zugang zu WISO. Diese bieten Zeitungsartikel an. Die Authentifizierung findet über den SSO der Hochschule/Uni statt.

**URL des Digitalangebots der Bibliothek**
[https://www.wiso-net.de/](https://www.wiso-net.de/)

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
Auf der Webseite steht "Provided by Genios", daher denke ich dass es sich um Genios hadelt

**Comment by schaphil** [comment]
Das funktioniert in der Regel nur mit VPN aus dem Netzwerk der Hochschule.

**Comment by PascalKoe** [comment]
Das würde für einige natürlich den Komfort reduzieren aber als einen Dealbreaker würde ich das nicht ansehen.
Und da das ganze über Shibboleth funktioniert, denke ich, dass es bei genügenden auch ohne VPN funktioniert.
