### ISSUE TITLE
Bibliotheken in Baden-Württemberg

### ISSUE THREAD

**Issue by mojoaxel** [stefanw/voebbot#16]
**URL des Digitalangebots der Bibliothek**
_verschiedene.._

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**

### Genios
- https://bib-bawue.genios.de
  - Mediathek Neckarsulm
  - Mediothek Balingen
  - Stadtbibliothek Aalen
  - Stadtbibliothek Freiburg
  - Stadtbibliothek Ludwigsburg
  - Stadtbibliothek Offenburg
  - Stadtbibliothek Reutlingen
  - Stadtbibliothek Ulm
  - Stadtbücherei Albstadt
  - Stadtbücherei Backnang
  - Stadtbücherei Biberach
  - Stadtbücherei Fellbach
  - Stadtbücherei Nürtingen
  - Stadtbücherei Tübingen
  - Stadtbücherei Waiblingen

### Munzinger
- **58021**: Mediathek Neckarsulm
- **50107**: Mediothek Balingen
- **50016**: Stadtbibliothek Aalen
- **50945**: Stadtbibliothek Freiburg
- **52134**: Stadtbibliothek Ludwigsburg
- **52803**: Stadtbibliothek Offenburg
- **50095**: Stadtbibliothek Reutlingen
- **53600**: Stadtbibliothek Ulm
- ~~Stadtbücherei Albstadt~~
- **50420**: Stadtbücherei Backnang
- **50407**: Stadtbücherei Biberach
- **50933**: Stadtbücherei Fellbach
- **52724**: Stadtbücherei Nürtingen
- **53504**: Stadtbücherei Tübingen
- **53700**: Stadtbücherei Waiblingen

**Comment by PascalKoe** [comment]
Stadtbibliothek Ulm on theire login form:

> Wir bitten Sie, Ihre Nutzung auf höchstens 35 Artikel/Downloads pro Monat anzulegen. Für das Laden eines Ganzheft-PDFs sind mindestens zwei Abrufe zu zählen. Unser Nutzungskontingent über den Dienstleister GENIOS ist begrenzt. Nur so können alle Bibliotheksnutzer das Presseportal gleichermaßen nutzen.

Therefore I think we shouldn't add Ulm as a provider.
