### ISSUE TITLE
Error on tab when loading article

### ISSUE THREAD

**Issue by janstuemmel** [stefanw/voebbot#17]
Getting' following error message in the tab when i load a paywall article: `OpenID authentication failed for code 'null'!` 
I was using latest master branch as plugin...

**Comment by vauzet0** [comment]
same here 🤔

**Comment by stefanw** [comment]
Leider haben die Verlage Druck ausgeübt und die Pressedatenbanken beim VÖBB sind vorübergehend gesperrt. Siehe auch: https://twitter.com/stefanwehrmeyer/status/1373222472796020737

**Comment by stefanw** [comment]
Genios ist nun wieder verfügbar. Allerdings mit Captcha bei öfteren Zugriffen.
