### ISSUE TITLE
Captcha bei Genios

### ISSUE THREAD

**Issue by stefanw** [stefanw/voebbot#19]
Bei häufigeren Aufrufen erscheint nun bei Genios ein Captcha.

<img width="517" alt="Screenshot 2021-03-26 at 15 28 03" src="https://user-images.githubusercontent.com/78356/112655591-76643400-8e48-11eb-80bb-941e32c5b580.png">

**Comment by sistein** [comment]
Gegen Captchas kann die Verlagerung nach China helfen. Es entlastet die Nerven schon beim normalen Surfen wenn man nicht selbst lösen muss ;-)

**Comment by stefanw** [comment]
Man wird nun aufgefordert zum entsprechenden Tab zu wechseln.
