### ISSUE TITLE
Installation not possible via zip file (on Mac Chrome)

### ISSUE THREAD

**Issue by tillnagel** [stefanw/voebbot#2]
Tried to install plugin for Chrome Mac 89.0.4389.90 via the described installation method, i.e. dragging the downloaded ZIP file onto the Extension page. Chrome simply "downloads" the ZIP file anew. 

I had to switch the Extension page to Developer mode and choose the extracted folder of the extension.

**Comment by stefanw** [comment]
Extension has been submitted to the chrome web store. If they accept, this will be much easier.

**Comment by stefanw** [comment]
Jetzt im [Chrome Web Store](https://chrome.google.com/webstore/detail/voebbot/edafomjglmkfbiieocpflnhfdmikkhbo?hl=de) verfügbar!

**Comment by stefanw** [comment]
Die ZIP-Version sollte deinstalliert werden und mit der Chrome-Store-Version ersetzt werden, um zukünftige Updates automatisch zu bekommen.

**Comment by tillnagel** [comment]
Top. Funktioniert einwandfrei.
