### ISSUE TITLE
Extension auf dem Smartphone nutzen?

### ISSUE THREAD

**Issue by mpagels** [stefanw/voebbot#22]
Ist es möglich die Extension mit `Firefox for Android` zu nutzen?

Ich habe versucht die `.xpi` auf dem Smartphone oder Tablet zu öffnen aber das ist nicht möglich. Sollte das funktionieren?
Mein "File Explorer" hat noch nicht mal erkannt, dass man das mit Firefox öffnen könnte.

Gibt es noch eine andere Möglichkeit die Extension mobil zu nutzen?

Und wenn ich helfen kann, sagt gerne Bescheid.

**Comment by stefanw** [comment]
[Sie können in Firefox für Android eine begrenzte Anzahl von Erweiterungen aus dem Programm für empfohlene Erweiterungen installieren und damit weitere Funktionen hinzufügen.](https://support.mozilla.org/de/kb/add-ons-finden-und-installieren-firefox-android).

VÖBBot ist nicht in den Firefox-Add-On-Store aufgenommen worden (zu spezifisch, man braucht Account zur Nutzung) und wird damit wohl auch nie in das „Programm für empfohlene Erweiterungen“ kommen.

**Comment by mpagels** [comment]
> Zumindest in `Fennec` oder `Firefox for Android Nightly` sind weitere Addons via (eigener) Collection möglich, siehe [Mozilla Blogbeitrag](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/).
> 
> 

Danke dir. Ich schaue es mir mal an.

**Comment by stefanw** [comment]
Mittlerweile ist die Extension auch gelistet als Mozilla Add-On: https://addons.mozilla.org/de/firefox/addon/bibbot/

Falls das hilft, ich habe hier eine Collection zum Testen erstellt, die nur BibBot enthält: https://addons.mozilla.org/de/firefox/collections/16594267/bibbot/

**Comment by BenutzerEinsZweiDrei** [comment]
Bei mir klappt es nicht. Habe auf Android Firefox Nightly aus dem Playstore. Die Collection hinzugefügt. Bibbot ist in neuster Version installiert. Wenn ich über die Einstellungen den Testartikel anzeigen will, zeigt sich Bibbot mit der Fehlermeldung "Beim Extrahieren der Artikeldaten trat ein Fehler auf."

Mache ich etwas falsch oder gibt es irgend eine andere Möglichkeit Bibbot über Android zu nutzen?
