### ISSUE TITLE
Süddeutsche Plus will nicht

### ISSUE THREAD

**Issue by niwi-hh** [stefanw/voebbot#31]
Wenn ich Artikel von SZ Plus öffne, wird unter dem Artikelanfang zwar die "VÖBBot-Animation" eungeblendet. Es kommt aber nicht zum Öffnen des Textes, obwohl er in Genios verhanden ist. Es öffnet sich auch kein zusätzlicher Tab.

Konkretes Beispiel:
https://www.sueddeutsche.de/kultur/britney-spears-doku-framing-britney-spears-amazon-1.5253812?reduced=true

Artikel anderer Seiten (z.B. Zeit, Welt) funktionieren. 

Ich nutze Version 0,13 zusammen mit einem  Zugang für die Bücherhallen Hamburg.

**Comment by stefanw** [comment]
Fixed in 0.14.0
