### ISSUE TITLE
saechsische.de

### ISSUE THREAD

**Issue by schnurpser** [stefanw/voebbot#35]
**URL der Nachrichtenseite**
https://www.saechsische.de

**URL zu einem Artikel mit Paywall**
https://www.saechsische.de/sachsen/die-dresdner-lehrerin-und-ihre-radikale-sekte-5418484-plus.html

**Ist die Nachrichtenseite bei Genios enthalten?**
Bitte bei Genios https://bib-voebb.genios.de/ unter Quellen -> Alle Quellen prüfen.

Ja   (mind. über https://www.ebibo-dresden.de/)

**Comment by thk12** [comment]
würde mich auch freuen, wenn die saechsische.de unterstützt wird

**Comment by Priphy** [comment]
Um das vielleicht etwas klarer zu formulieren: Die Seite ist definitiv bei genios enthalten und hat dort das Kürzel SZO.
