### ISSUE TITLE
Stadtbibliothek Leipzig

### ISSUE THREAD

**Issue by forenta** [stefanw/voebbot#40]
**URL des Digitalangebots der Bibliothek**
https://stadtbibliothek.leipzig.de/online-angebote/

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**

[Genios](https://stadtbib-leipzig.genios.de/), [Munzinger](https://munzinger.stadtbibliothek.leipzig.de), [PressReader](https://pressreader.stadtbibliothek.leipzig.de/).

**Comment by stefanw** [comment]
Wurde hinzugefügt!
