### ISSUE TITLE
not working with Zeit Online anymore

### ISSUE THREAD

**Issue by WolfgangDpunkt** [stefanw/voebbot#42]
On Zeit.de, the current version 0.17 does not work. Even the example page (https://www.zeit.de/2021/11/soziale-ungleichheit-identitaetspolitik-diskriminierung-armut-bildung) does not activate the plugin (macOS, Firefox 88) 
But its a great plugin! :-)

**Comment by mpagels** [comment]
The example page did work for me. Just tested it. And used the plugin (v.0.17 on zeit.de) for another article. Worked very well. Maybe the problem was just temporary?
(macOS, Firefox 88 as well)

**Comment by WolfgangDpunkt** [comment]
Thank you for your comment.
I have continued to try around: And as soon as I open the ZEIT online page in a Firefox private mode window, it works again.

But I don't know why, I disabled all addons except voebbot, deleted the cookies of the page....nothing helps, in normal mode it doesn't work, in private it does.

But that's ok :-)

**Comment by andreasmuellerka** [comment]
I have the same problem. Spiegel.de works fine, but on zeit.de no plus article is showed. The test article is not loaded, too. What I have done so far? Cleared cache, cleared browser history and after that, deleted the whole firefox profile. Even after starting with a new profile, the example article was not shown. Private mode or normal mode, nothing works. Firefox version is 88.

**Comment by stefanw** [comment]
Should be fixed in 0.17.2.
