### ISSUE TITLE
Wrong article delivered (Spiegel Plus)

### ISSUE THREAD

**Issue by impeira** [stefanw/voebbot#43]
A wrong article from genios is getting inserted in the following Spiegel Plus article:
https://www.spiegel.de/familie/leben-im-alter-die-grossmutter-hortet-ihre-schaetze-die-enkelin-ist-fuer-minimalismus-a-99ef96c1-c614-4212-b1bb-74a5830284e3

Suggestion: When the search result is not unique and/or is not an exact match maybe the first article should not be inserted. So there would be no confusion and the user has to look themself on genios for the article.

**Comment by mpagels** [comment]
The same thing was happening today when I searched for an article on spiegel. 

Let me know if I can help to fix this.

**Comment by stefanw** [comment]
Spiegel.de is tricky:

- It seems like many articles are not appearing in print and thus are not in Genios.
- Their SEO game is strong, they rewrite titles and teasers and no main 'original' content is available for search.

I added date range search to narrow down matching articles, but it might also be hit and miss.

If you find a better way to get the right article, let me know and I'll try to build it in.
