### ISSUE TITLE
Hochschul- und Kreisbibliothek Bonn-Rhein-Sieg

### ISSUE THREAD

**Issue by outbacker** [stefanw/voebbot#49]
**URL des Digitalangebots der Bibliothek**
https://www.h-brs.de/de/bib/datenbanken
https://www.h-brs.de/de/bib/ezb-readme
https://www.h-brs.de/de/bib/zeitschriften

Übersicht:
https://www.digibib.net/Digibib?SERVICE=TEMPLATE&SUBSERVICE=DIGILINK_BROWSE&VIEW=1044:Alle&LOCATION=1044&SID=MASTER:d933dac82dcfb798a750bf4985643f31&ACCESSCOND2=2&FUNC=AlphaView&LETTER=-&TERM=-

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
Genios via wiso-net (funktioniert bereits mit dem wiso-net non-SSO Zugang), Munzinger via digibib (aber nur Filmkritiken und Personensuche sind abonniert), [Rhein-Sieg Onleihe](https://www.onleihe.de/rhein-sieg/frontend/login,0-0-0-800-0-0-0-0-0-0-0.html?libraryId=1009) 

Proxy-Autokonfiguration: https://www.h-brs.de/files/proxy.pac

**Comment by stefanw** [comment]
Hi, danke für die Recherche. Habe ich es richtig verstanden, dass es via wiso-net schon funktioniert und keine Änderungen erforderlich sind? Dann schließe ich das Issue.

**Comment by outbacker** [comment]
Es funktioniert über einen Proxy, welchen man in den Browsereinstellungen hinterlegen kann, das Login über die im Plugin hinterlegte Kennung schlägt fehl. Es kann aber durchaus sein, dass die Bibliothek den Zugriff auf wiso-net ausschließlich per Proxy oder vor Ort erlaubt. Werde mich da mal informieren.
