### ISSUE TITLE
Fehlermeldung beim Versuch der Chromium-Installation; 

### ISSUE THREAD

**Issue by ajuvo** [stefanw/voebbot#5]
"Unrecognized manifest key 'browser_specific_settings'."

Version 89.0.4389.82 (Offizieller Build) Built on Ubuntu , running on Ubuntu 16.04 (64-Bit)

Ausgabe:

default_title": "VOEBBot"
  },
  "browser_specific_settings": {
    "gecko": {
      "id": "voebbot@stefanwehrmeyer.com",
      "strict_min_version": "57.0",
      "update_url": "https://stefanw.github.io/voebbot/updates.json"
    }
  }
}

**Comment by tillnagel** [comment]
See #1

**Comment by stefanw** [comment]
"Unrecognized manifest key 'browser_specific_settings'." ist nur eine Warnung, die ignoriert werden kann. Der Eintrag ist für Firefox wichtig. Momentan gibt es nur einen Build für Chrome/Firefox, daher wird da keine unterschiedliches manifest ausgeliefert.
