### ISSUE TITLE
General-Anzeiger Bonn / Bonner General-Anzeiger

### ISSUE THREAD

**Issue by outbacker** [stefanw/voebbot#50]
**URL der Nachrichtenseite**
https://ga.de/

**URL zu einem Artikel mit Paywall**
https://ga.de/region/voreifel-und-vorgebirge/swisttal/flutnacht-im-rhein-sieg-kreis-spd-kritisiert-kreisbrandmeister_aid-62527137

**Ist die Nachrichtenseite bei Genios enthalten?**
Bitte bei Genios https://bib-voebb.genios.de/ unter Quellen -> Alle Quellen prüfen.

Ja, Abkürzung ist GAZ 
https://www.wiso-net.de/dosearch?&dbShortcut=GAZ

**Comment by stefanw** [comment]
Ist drin, wird Teil des nächsten Releases.

**Comment by outbacker** [comment]
Besten Dank, Stefan!
