### ISSUE TITLE
Virtuelle Bücherei Wien

### ISSUE THREAD

**Issue by pihokkerr** [stefanw/voebbot#54]
**URL des Digitalangebots der Bibliothek**
https://buechereien.wien.gv.at/B%C3%BCchereien-Wien/Angebote/E-Medien

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
Onleihe, Overdrive, kiosk.at, PressReader

**Comment by stefanw** [comment]
Ohne Genios leider gerade nicht abbildbar.
