### ISSUE TITLE
Hamburger Morgenpost (Mopo /M+)

### ISSUE THREAD

**Issue by niwi-hh** [stefanw/voebbot#57]
**URL der Nachrichtenseite**
https://www.mopo.de
Bisher war die Mopo ohnehin fast komplett kostenlos. Seit wenigen Tagen gibt es aber täglich vermehrt Artikel hinter einer Paywall.

**URL zu einem Artikel mit Paywall**
https://www.mopo.de/hamburg/vor-29-jahren-stillgelegt-das-wird-jetzt-aus-dem-schellfischtunnel/?reduced=true
Direkt in Genios wird dieser Artikel auch gefunden. Über die Mopo-Webseite schlägt das Addon aber nicht an.

**Ist die Nachrichtenseite bei Genios enthalten?**
Ja. Getestet mit den Hamburger Bücherhallen. Dort wird ein Großteil der Hamburger Leserschaft mit diesem Addon ja auch Kunde sein.

**Comment by stefanw** [comment]
Die Mopo ist nicht in meinem Bibliothekszugang enthalten, daher kann ich das leider nicht selbst durchtesten.

**Comment by niwi-hh** [comment]
Das Kürzel in Genios lautet "MOPO". 

Wie wäre es, wenn du eine Spendenmöglichkeit anbietest. Ich bin sicher, dass du schnell genügend Geld für einen Zugang der Hamburger Bücherhallen zusammen hättest. Damit hättest du dann einen erheblich größeren Zugriff auf die deutsche Presselandschaft als von Berlin aus. Davon würden alle Nutzer des Addons profitieren.
