### ISSUE TITLE
Bot funktioniert auf Handelsblatt.com nicht

### ISSUE THREAD

**Issue by alx080** [stefanw/voebbot#59]
**URL der Nachrichtenseite**
https://handelsblatt.com
**URL zu einem Artikel mit Paywall**
Alle Handelsblatt-Artikel

**Ist die Nachrichtenseite bei Genios enthalten?**
Ja

**Leider kommt keine Aktion oder Animation wenn ich versuche Handelsblatt-Artikel zu lesen, auf anderen Seiten funktioniert der Bot einwandfrei! Nutze den Zugang über Voebb.**

BR, Alex

**Comment by stefanw** [comment]
Sollte in 0.18.1 wieder funktionieren.
