### ISSUE TITLE
Add supported sites to website

### ISSUE THREAD

**Issue by varac** [stefanw/voebbot#60]
Thanks for this awesome app!
Can you please add the supported sites to the website ?

And I am also wondering if you can also use this app with an *account* of any other library, like buecherhallen.de ?

**Comment by varac** [comment]
I have two other issues regarding the website: 

* Why is the description on the website striked through ? It's a bit confusing and I don't get it if this is meant as a joke.
* `Leider steht der Download aus Gründen zur Zeit nicht zur Verfügung.` What are the reasons ?

**Comment by stefanw** [comment]
Es gab da mal einen [Zwischenfall](https://netzpolitik.org/2021/abgeschaltete-browser-erweiterung-voebbot-der-weg-hinter-die-paywall-bleibt-kompliziert/). Hoffe die Gemüter haben sich mittlerweile beruhigt.

**Comment by varac** [comment]
Ah good to know  :crossed_fingers: . Wouldn't it be good to link to that article from the website, so you get a bit of context ? Anyhow, works out of the box with a buecherhallen account, thanks again !!

**Comment by stefanw** [comment]
Website has been updated: https://stefanw.github.io/voebbot/
