### ISSUE TITLE
https://ssl.muenchen.de/

### ISSUE THREAD

**Issue by MarinaInMunich** [stefanw/voebbot#63]
**URL des Digitalangebots der Bibliothek**
https://https://ssl.muenchen.de/

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
Ja, Munzinger via Pressreader.com

**Comment by stefanw** [comment]
Ohne Genios funktioniert das leider nicht mehr.
