### ISSUE TITLE
Stadtbibliothek Mannheim

### ISSUE THREAD

**Issue by levinuss** [stefanw/voebbot#65]
**URL des Digitalangebots der Bibliothek**
https://www.mannheim.de/de/bildung-staerken/stadtbibliothek/digitale-angebote

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
Genios (https://bib-mannheim.genios.de/)

**Comment by stefanw** [comment]
Fixed in ef146cf5f74248f98724318e14dd072ebaf4dc87.
