### ISSUE TITLE
Bibliothek Mannheim

### ISSUE THREAD

**Issue by wuttkea** [stefanw/voebbot#68]
**URL des Digitalangebots der Bibliothek**
https://www.mannheim.de/de/bildung-staerken/stadtbibliothek

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
ja, https://www.mannheim.de/de/bildung-staerken/stadtbibliothek/digitale-angebote/genios-ebib-das-presseportal

**Comment by CarlssonD** [comment]
Bib Mannheim ist leider nicht mehr gelistet. kann man die wieder einsetzen?
Vielen Dank im voraus!!!!
