### ISSUE TITLE
Fernuni Hagen WISO über Proxy

### ISSUE THREAD

**Issue by Daedalus3** [stefanw/voebbot#74]
Auch die Fernuni Hagen stellt den Studenten den Zugriff auf die WISO-Datenbank zur Verfügung, leider jedoch nicht via SSO, sondern lediglich über einen zwischengeschalteten Proxy. Es wäre toll, wenn der vöbbot diesen Proxy unterstützen würde

**URL des Digitalangebots der Bibliothek**
https://www.ub.fernuni-hagen.de/datenbankenlieferdienste/showdatabase.html?id=868

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
WISO (GENIOS)

Der Zugriff auf die Datenbank erfolgt dann über:

https://www-wiso-net-de.ub-proxy.fernuni-hagen.de/

**Comment by Daedalus3** [comment]
Kleine Ergänzung, die Suche wird dann über https://www-wiso-net-de.ub-proxy.fernuni-hagen.de/dosearch ausgeführt.

**Comment by stefanw** [comment]
Gerne Feedback, ob es mit den Änderungen klappt!

**Comment by Daedalus3** [comment]
Herzlichen Dank! Die Integration klappt grundsätzlich (z.B. auf Welt.de), die Artikelausbeute ist allerdings mau, was aber vermutlich eher an der zur Verfügung stehenden Datenbank liegt.
