### ISSUE TITLE
Stadtbibliothek Ulm

### ISSUE THREAD

**Issue by monsimeister** [stefanw/voebbot#77]
**URL des Digitalangebots der Bibliothek**
https://stadtbibliothek.ulm.de/online/digitales-presseportal

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
Genios - https://bib-bawue.genios.de/

**Comment by stefanw** [comment]
Added in next release 0.18.9.
