### ISSUE TITLE
FAZ.net

### ISSUE THREAD

**Issue by derspotter** [stefanw/voebbot#8]
**URL der Nachrichtenseite**
faz.net

**URL zu einem Artikel mit Paywall**
https://www.faz.net/aktuell/politik/inland/f-a-z-exklusiv-die-trophaeen-der-jungen-union-17250230.html

**Ist die Nachrichtenseite bei Genios enthalten?**
nein, leider nicht

**Comment by stefanw** [comment]
Ohne bei Genios gelistet zu sein, kommen wir hier leider nicht weiter.

Alternativen: pressreader.com, das auch auch im VÖBB-Konto enthalten ist, gibt einem Zugriff auf Bilder der aktuellen Print-FAZ, so weit ich das sehe. Leider lässt sich das nicht sinnvoll in VÖBBot integrieren.

**Comment by DonkeeeyKong** [comment]
Also bei mir gibt es FAZ.net bei Genios. Wäre super, das einzubauen. :)
