### ISSUE TITLE
Leipziger Städtische Bibliotheken 

### ISSUE THREAD

**Issue by leisteo** [stefanw/voebbot#85]
**URL des Digitalangebots der Bibliothek**
https://stadtbibliothek.leipzig.de/online-angebote

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
[Genios](https://genios.stadtbibliothek.leipzig.de/)
[Munzinger](https://munzinger.stadtbibliothek.leipzig.de/corporate/)
[Pressreader](https://pressreader.stadtbibliothek.leipzig.de/catalog)

**Comment by leisteo** [comment]
Wenn ich mich auf der Seite einlogge, sehe ich das.
https://stadtbibliothek.leipzig.de/online-angebote
Und bei Genios dann das: 
https://genios.stadtbibliothek.leipzig.de/dosearch

**Comment by stefanw** [comment]
Screenshots wären gut. Noch besser nach dem Einloggen von jeder Seite das HTML speichern (via Datei -> Seite speichern...) und hier posten. Das Add-On muss erkennen, ob der Login erfolgreich war und da weiß ich nicht, wie das hier zu erkennen ist.

**Comment by stefanw** [comment]
Habe das mal versucht, Bibliothek ist jetzt in den Einstellungen verfügbar in Version 0.20.3+. Gerne mal ausprobieren.

**Comment by leo-liar** [comment]
Hallo @stefanw! ich hoffe, es ist in Ordnung, wenn ich diesen geschlossenen Issue wiederverwende ...

Ich habe mir kürzlich eine Leipziger Bibliothekszugang eingerichtet und *BibBot* getetestet, aber leider klappt der Aufruf bzw. das Einbinden von Artikel (z.B. [spiegel.de](https://www.spiegel.de/)) noch nicht so richtig.

Z.B. dieser Artikel von Spiegel+ hier: [»Man darf die menschliche Dummheit nie unterschätzen«](https://www.spiegel.de/kultur/yuval-noah-harari-ueber-den-ukraine-krieg-man-darf-die-menschliche-dummheit-nie-unterschaetzen-a-a7fe6a2c-c07e-433b-8d2f-be90898a7f00)
Es öffnet sich zwar ein Genios-Tab beim Aufruf, aber schon der automatische Login klappt leider nicht. Wenn ich mich zuvor schon angemeldet habe, dann wird aber die Suche (in der Genios-Datenbank) nicht automatisch aufgerufen/gestartet (das Feld bleibt leer) bzw. wenn ich vorher selbst via Genios gesucht habe, wird immer nur meine letzte Suche dort angezeigt.

Und auch wenn ein Artikel dort zu finden ist, wird er nicht automatisch auf der Spiegel-Seite eingebunden. Hier erscheint stets nur die `BibBot - Pressedatenbank wird aufgerufen...`-Meldung, ohne dass etwas passiert.

---

Du hattes zuvor geschrieben, dass die Login-Erkennung ggf. schwierig ist und dass du eventuell Zugangsdaten benötigst, um weiter zu testen - ich könnte dir meine zukommen lassen, sofern noch Bedarf besteht. (Gib kurz Bescheid, dann schicke ich dir diese per E-Mail.)

**Comment by leisteo** [comment]
Was leo-liar schreibt habe ich auch beobachtet. War nur leider noch nicht dazu gekommen, es so schön aufzuschreiben. Der Tab zum Einloggen bei Genios öffnet sich mithilfe des Bots. Wenn ich mich dann aber eingeloggt habe, geht es nicht weiter. Wenn ich schon eingeloggt bin, rödelt der Bot eine Weile, der Artikel wird aber nicht geöffnet.
