### ISSUE TITLE
SZ Problem

### ISSUE THREAD

**Issue by Wikinaut** [stefanw/voebbot#86]
https://www.sueddeutsche.de/reise/karneval-in-venedig-tourismus-coronavirus-italien-1.5534763?reduced=true
triggert zwar, aber dann geht es nicht weiter:

Es kommt nur das:
![grafik](https://user-images.githubusercontent.com/1151915/155745554-de90dc60-a504-4eeb-8e89-568ccbe9b0d7.png)

Ziel:
https://bib-voebb.genios.de/document/SZDE__5850c0181389433c08464775ab8dbf19f226f509

**Comment by Wikinaut** [comment]
Habe andere geprüft: die funktionieren wie gehabt.

**Comment by stefanw** [comment]
Sollte in 0.20.1 behoben sein.
