### ISSUE TITLE
Welt.de: Veränerte Printartikel werden mit Suche nach Überschriften nicht gefunden

### ISSUE THREAD

**Issue by niwi-hh** [stefanw/voebbot#87]
Ich möchte auf einen Artikel in Welt,.de hinweisen, der durch das Addon nicht gefunden wird. Ich bin mir nicht sicher, ob er allerdings tatsächlich ausreichend ähnlich in der Printausgabe von "Welt am Sonntag" erschien. Zumindest der Online-Teaser startet anders, als der Artikel in Genios. Beide Veröffentlichungen gehen auf alle Fälle auf das selbe Interview mit Monika Maron zurück. Man kann den Artikel auch mit Hilfe des Teasers in Genios finden, wenn man zum Suchen Teile der wörtlichen Rede von Monika Maron nimmt. Hier das konkrete Beispiel:

https://www.welt.de/kultur/plus236969261/Monika-Maron-Ich-bin-gegen-Quoten-Man-sieht-ja-wohin-sie-fuehren.html

Textausschnitt, mit dem die Suche gelingen würde:
"gut an. Das Make-up ist tadellos."

Könnte das Addon hier noch Erfolg haben, oder wird dies bei solch starken Bearbeitungen aussichtslos?

**Comment by stefanw** [comment]
Fixed in 073a0ae07b127c7415d05b325d21f30a3b0c8c9f
