### ISSUE TITLE
Zeit Online: finds different article from same "series"

### ISSUE THREAD

**Issue by derhuerst** [stefanw/voebbot#88]
Thanks for this project! 🙌

I just wanted to use Voebbot to pull the full text for this Zeit Online article: https://www.zeit.de/kultur/2022-02/voelkerrecht-russland-ukraine-krieg-massnahmen-dana-schmalz-interview

Because the extensions seems to search for the first sentence of the text and then picks any (?) match from GENIOS, and because the article is part of a series whose articles all start with the same paragraph, it picks the wrong one:

> Zeit online vom 19.02.2022, Nr. 1
> Sally Haslanger
> "Der Begriff 'Frau' sollte mehr als bloß eine Bedeutung haben"

**Comment by stefanw** [comment]
Ich habe in v0.20.2 Suche mit Datumseingrenzung implementiert. Mal schauen, ob das schief geht, wegen Online/Print-Datum-Diskrepanzen, aber für zeit.de sollte es gehen.
